Follow/unfollow functionality to button to publictimeline, missing fr…
ITU-BDSA23-GROUP12/Chirp pull request #294
Opened 2023-11-22 07:15 UTC by Maquidos

…om privatetimeline.

Co-authored-by: chat.openai.com

2023-11-22 20:57 UTC, allanzigge commented on src/Chirp.Infrastructure/AuthorRepository.cs
> +    var unFollowingAuthor = await _context.Authors.FirstOrDefaultAsync(a => a.Name == unFollowingName);
Hvorfor bruges email(l. 89) og derefter name

2023-11-23 13:23 UTC, palleBrandt commented on src/Chirp.Web/Pages/Public.cshtml
> +@inject IAuthorRepository AuthorRepository
I think this should be removed

2023-11-23 13:27 UTC, palleBrandt requested changes
I made a comment with the requested change

2023-11-23 14:33 UTC, palleBrandt approved these changes
Looks good

2023-11-23 14:33 UTC, merged