initial setup Architecture of deployed application
ITU-BDSA23-GROUP12/Chirp pull request #377
Opened 2023-12-15 17:14 UTC by Maquidos

2023-12-17 07:05 UTC, palleBrandt approved these changes
Very good!! Super cool illustration!

Only thing is i think theres a misspelling in the illustration. It says dbsa.... instead of bdsa.... :)

2023-12-17 11:40 UTC, allanzigge requested changes
Ser vildt godt ud!

Lidt stavefejl men tænker vi klarer dem til sidst? 
Ser referencerne rigtige ud for jer? Jeg ser bare teksten
Og så som @palleBrandt skriver, grafen har en lille typo :)

2023-12-19 12:55 UTC, allanzigge approved these changes
Go for it

2023-12-19 14:35 UTC, kartoffelmozart approved these changes

2023-12-20 10:31 UTC, RazzerTazzer approved these changes
loooks good

2023-12-21 08:09 UTC, merged