add short about license
ITU-BDSA23-GROUP12/Chirp pull request #378
Opened 2023-12-17 11:40 UTC by allanzigge

2023-12-18 13:26 UTC, Maquidos requested changes

2023-12-18 13:26 UTC, Maquidos commented on docs/report.md
> +It became clear to us that choosing a license is important to us as developers and to provide guidelines for other developers. This is of course even more relevant if the application were to stay and
why? XD
måske bare lige knytte en enkelt grund til hvorfor det er vigtig

2023-12-19 06:44 UTC, palleBrandt requested changes
Super godt!

Dog enig med Marcus' kommentarer. Men kan sagtens være at det med MIT er underforstået og det bare er mig som skal læse op.

2023-12-19 14:39 UTC, palleBrandt approved these changes

2023-12-19 14:52 UTC, kartoffelmozart approved these changes

2023-12-20 10:29 UTC, RazzerTazzer approved these changes
looks good

2023-12-20 17:31 UTC, Maquidos approved these changes
skide lækkert altså!

2023-12-21 08:10 UTC, merged