llm part
ITU-BDSA23-GROUP12/Chirp pull request #379
Opened 2023-12-17 11:41 UTC by allanzigge

Ved ikke om der er mere jeg burde komme ind på?

2023-12-18 13:05 UTC, Maquidos requested changes

2023-12-18 13:05 UTC, Maquidos commented on docs/report.md
> +We tried asking ChatGPT when hitting an error that we could not figure out why we recieved. ChatGPT could actually help finding the error sometimes, making this valueable to us.
Jeg synes også man kunne komlimentere Chatten for at være god til at gennemskue sammenhænge over flere domæner. Dokumentation der beskriver domæner (Azure, Github, ASP.NET) beskriver jo det enkelte domæne,  og selvom der ofte kan findes guides til hvordan man intergere andre domæner, rammer det ikke altid lige den situation man selv sidder i. Der sparre chatten os en del hovedpine i at skulle forstå dokumentation for flere domæner til bunds for at intergere dem med hinanden, da den jo er skab til at finde sammenhænge mellem dokumentation.

2023-12-19 08:20 UTC, palleBrandt commented on docs/report.md
> +We tried asking ChatGPT when hitting an error that we could not figure out why we recieved. ChatGPT is often helpful with both finding but also explain what the error is to understand _why_ we get th
Måske skriv noget om hvordan chatgpt også er god til at bruge til at pege en i en retning at hvad man skal søge videre på, give nogle keywords og så videre. Bare lige for sådan at vise at man ikke kun afhænger af ChatGpt.

2023-12-19 08:24 UTC, palleBrandt commented on docs/report.md
> +We tried asking ChatGPT when hitting an error that we could not figure out why we recieved. ChatGPT is often helpful with both finding but also explain what the error is to understand _why_ we get th
```suggestion
We tried asking ChatGPT when hitting an error that we could not figure out why we recieved. ChatGPT is often helpful with both finding but also explain what the error is to understand _why_ we get the error. This has been great to get a better understanding of what we need to fix to make good and functional code. Furthermore ChatGPT has proven to be a solid tool for discovering keywords and to figure out what documentation needs to be delved into.
```

2023-12-19 08:24 UTC, palleBrandt requested changes
Very good. I added a suggestion about an add on sentence. This talks about the use of chatgpt.

2023-12-19 12:06 UTC, palleBrandt approved these changes

2023-12-19 12:24 UTC, merged