Write section about Architecture in the Small.
ITU-BDSA23-GROUP12/Chirp pull request #381
Opened 2023-12-17 15:32 UTC by palleBrandt

Still needs uml package diagram

2023-12-17 20:55 UTC, allanzigge commented on docs/report.md
> +When looking at figure \ref{OnionDiagram}, dependencies must be read goin inwards toward the center of the illustration. In there we have the Chip.Core package. Besides building Chirp with clean arch
goinG

2023-12-17 21:00 UTC, allanzigge commented on docs/report.md
> +The outermost layer is the entry point for our Chirp application. In the code this is the Chirp.Web package, which holds a RazorPage Application. This package depends on both the Chirp.Core and the C
Chirp.Web bliver hyper-link? 
![image](https://github.com/ITU-BDSA23-GROUP12/Chirp/assets/118464722/c65bde33-aa96-44f7-8753-88f78391be01)

2023-12-17 21:03 UTC, allanzigge requested changes
Enkelte kommentarer, ellers er det nice

2023-12-18 12:32 UTC, Maquidos commented on docs/report.md
> +When looking at figure \ref{OnionDiagram}, dependencies must be read goin inwards toward the center of the illustration. In there we have the Chip.Core package. Besides building Chirp with clean arch
tyoes?

2023-12-18 14:11 UTC, palleBrandt commented
I made the requested changes.

2023-12-19 12:39 UTC, allanzigge requested changes

2023-12-19 12:39 UTC, allanzigge commented on docs/report.md
> +When looking at figure \ref{OnionDiagram}, dependencies must be read goin inwards toward the center of the illustration. In there we have the Chip.Core package. Besides building Chirp with clean arch
```suggestion
When looking at figure \ref{OnionDiagram}, dependencies must be read going inwards toward the center of the illustration. In there we have the Chip.Core package. Besides building Chirp with clean architecture, we also make use of the repository pattern to allow for abstraction and organization of datahandling. In the _Chirp.Core_ package we hold two repository-pattern specific classes. The Data Transfer Objects (DTO), and the repository interfaces. This follows the DDD and the repository pattern, placing an abstraction of the business logic at the very center of our application.
```

2023-12-19 12:39 UTC, allanzigge commented on docs/report.md
> +The next layer in the architecture is the data layer which manifests in Chirp as the _Chirp.Infrastructure_ package. Here lies all classes related to the datahandling and databasemanagement. Followin
```suggestion
The next layer in the architecture is the data layer which manifests in Chirp as the _Chirp.Infrastructure_ package. Here lies all classes related to the data handling and database management. Following dependencies going towards the center, this package depend on the _Chirp.Core_ package, as it holds the implementation of the repository interfaces. This dependency shows how the architecture implements the Dependency Inversion principle, which states that implementations should depend on abstractions and not the other way around.
```

2023-12-19 13:20 UTC, allanzigge approved these changes

2023-12-19 14:40 UTC, palleBrandt commented on docs/report.md
> +When looking at figure \ref{OnionDiagram}, dependencies must be read goin inwards toward the center of the illustration. In there we have the Chip.Core package. Besides building Chirp with clean arch
I have fixed this typo

2023-12-20 10:26 UTC, RazzerTazzer reviewed
looks good

2023-12-20 10:26 UTC, RazzerTazzer approved these changes

2023-12-20 11:47 UTC, allanzigge approved these changes
Gutmann

2023-12-20 15:21 UTC, kartoffelmozart commented on docs/report.md
Du skriver "dependencies must be read going inwards toward the center", altså Web -> Infrastructure -> Core, men du beskriver strukturen outwards from the center, altså Core -> Infrastructure -> Web. Da jeg læste det blev jeg et øjeblik i tvivl om jeg havde misforstået onion strukturen, indtil jeg forstod hvad du mente. Hvis der er andre der blev forvirrede, så måske det skal ændres?

2023-12-20 15:46 UTC, kartoffelmozart requested changes

2023-12-20 15:46 UTC, kartoffelmozart commented on docs/report.md
Du skriver at i Core ligger implementationen af vores repository interfaces. Det lyder lidt som om du mener at klasserne som implementerer vores interfaces ligger dér, jeg tror det ville være mere tydeligt at sige at definitionen af vores interfaces ligger i Core.

2023-12-20 15:46 UTC, kartoffelmozart commented on docs/report.md
Til slut er der en typo på linie 23 ved __Chip.Core__, ellers mega godt! Jeg ved ikke om det er værd at ændre på noget, hvis det kun er forvirrende for mig.

2023-12-20 17:24 UTC, allanzigge commented on docs/report.md
Nu spørger jeg muligvis dumt, men siger man ikke at en klasse implementerer et interface?
Ikke at en klasse er en definition af et interface 

Ret mig endelig hvis jeg tager fejl

2023-12-20 20:10 UTC, palleBrandt commented on docs/report.md
Nu blev jeg selv lidt forvirret :) Er det denne sætning:

"The next layer in the architecture is the data layer which manifests in Chirp as the Chirp.Infrastructure package. Here lies all classes related to the datahandling and databasemanagement. Following dependencies going towards the center, this package depend on the Chirp.Core package, as it holds the implementation of the repository interfaces."

Kan godt se at den indskudte sætning nok ikke er så god på engelsk, det "it" som jeg mener holder implementationen er Infrastructure, og ikke Core. Kan godt forstå forvirringen da jeg lige har sagt Core. Ændrer det til et eksplicit "Chirp.Infrastructure" istedet :)

2023-12-20 20:12 UTC, palleBrandt commented on docs/report.md
Jeg har ændret til et mere eksplicit om hvilken package jeg snakker om, forstår godt forvirringen. :)

2023-12-20 20:48 UTC, allanzigge approved these changes

2023-12-20 22:14 UTC, kartoffelmozart approved these changes

2023-12-21 08:13 UTC, merged

2023-12-21 08:13 UTC, Maquidos reviewed
mums