366 process team work
ITU-BDSA23-GROUP12/Chirp pull request #388
Opened 2023-12-19 10:52 UTC by kartoffelmozart

pls tell me what else is needed on this one

2023-12-19 13:30 UTC, palleBrandt commented on docs/report.md
> +Below is a user flow diagram showing the process of an issue:
```suggestion
See figure \ref{The life of an issue}, a user flow diagram showing the process of an issue:
```

2023-12-19 13:30 UTC, palleBrandt commented on docs/report.md
> +Here comes a description of our domain model.
```suggestion
Our Application builds on two main consepts: Cheeps and Authors.

### Cheep
A Cheep is the understanding of a post, which holds a message from the author of the post. It has a refernce to its author and a knowlegde of when it was posted.

### Author
An Author represents the user in our program. The user can write posts (Cheeps), which is why they are named Author. An Author has references to all their Cheeps, as well as their name and email. It is possible to follow an Author; therefore, the Author also has references to the Authors who follow it and the Authors it follows.

Our domain model consists of two data entities, which depict the attributes of a 'Cheep' and an 'Author' in the context of our application. Figure \ref{domainModelImage} shows the two classes, 'Cheep' and 'Author,' with their fields and cardinality relationships between each other and within themselves. The 'Cheep' class has a one-to-one relationship with an 'Author' class, and an 'Author' class has a zero-to-many relationship with the 'Cheep' class. Furthermore the 'Author' class has a zero-to-many relationship with authors who follow it and a zero-to-many relationship with authors whom it follows.

![Illustration of the _Chirp!_ data model as UML class diagram.\lable{domainModelImage}](https://raw.githubusercontent.com/ITU-BDSA23-GROUP12/Chirp/main/docs/images/DomainModel.drawio1.png)
```

2023-12-19 13:31 UTC, palleBrandt commented on docs/report.md
> +![Illustration of the _Chirp!_ data model as UML class diagram.](docs/images/domain_model.png)
```suggestion
```

2023-12-19 13:32 UTC, palleBrandt requested changes
Very nice section.

I have added some minor suggestions for you to approve:
- [ ] We have accidentally deleted Marcus part about domainmodel, therefore i have suggested to reinsert it.
- [ ] A reference to the figure number.

2023-12-20 09:49 UTC, RazzerTazzer reviewed
I like the diagram alot. Im a little confused about backlog and if it fails the 'Ready for implementation'. If no, it seemss a new issue would be created. To me it makes more sense to have the arrow point to backlog again.

2023-12-20 13:52 UTC, allanzigge requested changes

2023-12-20 13:52 UTC, allanzigge commented on docs/report.md
> +The issues are created to match the project description provided by our professors Helge and Rasmus, or to match changes and details that we as a group or individually found relevant to implement.
fluff
```suggestion
The issues are created to match the project description provided by our professors, or to match changes and details that we as a group or individually found relevant to implement.
```

2023-12-20 13:52 UTC, allanzigge commented on docs/report.md
> +A team member then creates a GitHub branch with the name of the issue and starts on implementing the change described.
```suggestion
When a team member takes responsibility for an issue, he creates a branch linked to the issue with the name of the issue and starts on implementing the change described.
```

2023-12-20 13:52 UTC, allanzigge commented on docs/report.md
> +Often we have worked on larger/more fundemental changes in groups of 2-3 or as the whole team (mob programming).
```suggestion
Often we have worked on larger/more fundemental changes in groups of 2-3 or as the whole team (mob-/pair programming).
```

2023-12-20 13:52 UTC, allanzigge commented on docs/report.md
> +Upon merge, the issue is deleted.
```suggestion
Upon merge, the issue is closed and moved to Done in our project board.
```

2023-12-20 13:52 UTC, allanzigge commented on docs/report.md
> +![The life of an issue](https://github.com/ITU-BDSA23-GROUP12/Chirp/blob/366-process-team-work/docs/images/issue%20process.drawio.png)
```suggestion
![The life of an issue](https://github.com/ITU-BDSA23-GROUP12/Chirp/blob/366-process-team-work/docs/images/issue%20process.drawio.png?raw=true)
```

2023-12-20 16:23 UTC, kartoffelmozart commented on docs/report.md
> +Here comes a description of our domain model.
Den her del hører vist ikke til team work sektionen, muligvis det er bedre at ændre de ting på dens egen branch

2023-12-20 17:14 UTC, Maquidos commented on docs/report.md
> +Here comes a description of our domain model.
tror det er fordi at der vil være merge konflikt hvis ikke det er med

2023-12-20 17:15 UTC, Maquidos reviewed
looks nice

2023-12-20 20:28 UTC, palleBrandt approved these changes
Looks good with the new changes

2023-12-20 20:55 UTC, allanzigge approved these changes

2023-12-21 08:35 UTC, allanzigge requested changes

2023-12-21 08:35 UTC, allanzigge commented on docs/images/issue process.drawio.png
Need a few changes

2023-12-21 09:19 UTC, allanzigge approved these changes

2023-12-21 09:19 UTC, merged