Ready for some feedback
ITU-BDSA23-GROUP12/Chirp pull request #393
Opened 2023-12-20 09:27 UTC by RazzerTazzer

Would like some feedback

2023-12-20 12:07 UTC, allanzigge requested changes
Små ændringer

I release workflow har du en typo, der skal stå Executable i stedet for -bly

Og som skrevet i en kommentar tror jeg du har sat forkert billede ind til sidst?

2023-12-20 12:07 UTC, allanzigge commented on docs/report.md
> +This workflow consist of to jobs: 'BuildAndTest' and 'deploy'. Jobs can be run concurrently, but we need 'BuildAndTest' to run successfully, before we want to bother with deploying, hence the key wor
```suggestion
This workflow consist of to jobs: 'BuildAndTest' and 'deploy'. Jobs can be run concurrently, but we need 'BuildAndTest' to run successfully, before we want to bother with deploying, hence the key word 'needs', which means we only run the 'deploy' when 'BuildAndTest' is done. 
```

2023-12-20 12:07 UTC, allanzigge commented on docs/report.md
> +can manually be triggered on github or triggered by push to main. Again it sets up a .Net Core environment, restores the dependencies, builds and runs our test suite. Create and upload application  a
Mangler der noget her?

2023-12-20 12:07 UTC, allanzigge commented on docs/report.md
> +Then the second part of the workflow called 'deploy', takes care of uploading the new web-app to azure and deploy the new migrations to the azure database. See figure \ref{deploy-workflow}
```suggestion
Then the second part of the workflow called 'deploy', takes care of uploading the new web-app to Azure and deploy the new migrations to the Azure database. See figure \ref{deploy-workflow}
```

2023-12-20 12:07 UTC, allanzigge commented on docs/report.md
> +![UML Diagram of the deploy workflow\lable{deploy-workflow}](https://github.com/ITU-BDSA23-GROUP12/Chirp/blob/main/docs/images/Release-Workflow.drawio.png)
Er det et forkert billede?
```suggestion
![UML Diagram of the deploy workflow\lable{deploy-workflow}](https://github.com/ITU-BDSA23-GROUP12/Chirp/blob/main/docs/images/Release-Workflow.drawio.png?raw=true)
```

2023-12-20 12:35 UTC, Maquidos requested changes

2023-12-20 12:35 UTC, Maquidos commented on docs/report.md
> +This workflow is triggered when a branch is pushed or a pull request is created. It locates the source code, sets up a .NET Core environment. Then it downloads the missing if any dependencies are mis
```suggestion
This workflow is triggered when a branch is pushed or a pull request is created. It locates the source code and sets up a .NET Core environment. Then it downloads dependencies, if any are missing, builds the application and runs the test suite.
```

2023-12-20 19:59 UTC, palleBrandt commented on docs/report.md
> +During development of the application, we have used github workflows to automate some processes. It is defined in a YAML file and set to run on a trigger event. We have used one for Build and testing
```suggestion
During development of the application, we have used github workflows to automate some processes. It is defined in a YAML file and set to run on a trigger event. We have used one for Build and testing the application, one for creating a release on Github and one for deploying our .NET app to Azure and the schemas for our database. Workflows consist of one or more jobs, which have a sequence of steps that has to be executed. The diagrams below illustrate the steps and jobs of each workflow.
```

2023-12-20 20:04 UTC, palleBrandt commented on docs/report.md
> +This streamlining helped making releases with executables on Github, whenever our main was given new tags. We manually had to check if Main built and passed the tests before given new tags, but could
```suggestion
Initially this streamlining helped making releases with executables on Github, whenever our main was given new tags. However we have later switched to only release source code, as we have evolved _Chirp!_ into a web application. We manually had to check if Main built and passed the tests before given new tags, but could have been included. See figure \ref{Release-workflow}
```

2023-12-20 20:05 UTC, palleBrandt requested changes
This is super good stuff!

Small changes as we no longer release executables to Github but just sourcecode.

2023-12-20 20:47 UTC, allanzigge approved these changes

2023-12-20 21:12 UTC, kartoffelmozart approved these changes

2023-12-21 08:49 UTC, palleBrandt approved these changes

2023-12-21 08:49 UTC, Maquidos approved these changes
hmmm well its seems fine...

2023-12-21 08:49 UTC, merged